### ISSUE TITLE
Hook 'scencrypt' cannot be found

### ISSUE THREAD

**Issue by wazlecracker** [fuhry/initramfs-scencrypt#18]
Attempting to install on 5.2.11-1-MANJARO. 
When I get to step 10, I run `sudo mkinitcpio -p linux52` it starts building, but during the build it returns `==> ERROR: Hook 'scencrypt' cannot be found`. Followed the directions exactly.

**Comment by choopm** [comment]
Have you installed the hook via `makepkg -si` beforehand?

**Comment by wazlecracker** [comment]
I feel dumb. I forgot those flags! All good now.

**Comment by 2Belette** [comment]
Excaclty the same issue on Archlinux like OS. I have done a makepkg -si but got the same issue,any idea?
