### ISSUE TITLE
"pax format cannot archive sockets" errors whenn running mkinitcpio

### ISSUE THREAD

**Issue by casswarry0** [fuhry/initramfs-scencrypt#22]
When running mkinitcpio 3 errors of type "pax format cannot archive sockets" show up when creating the gzip-compressed initcpio image.
Solution: add "pkill -f gpg-agent -U 0" near the end of scencrypt-install to kill the instance of gpg-agent which opens the sockets which cause the error when creating the gzip-compressed initcpio image.

**Comment by fuhry** [comment]
I know I've seen this on my laptop in the past, but it appears to be resolved in the latest master. I don't see an explicit removal of the socket. Going to close it out, feel free to reopen if you observe this again.
