### ISSUE TITLE
Support for root partitions/early userspace

### ISSUE THREAD

**Issue by farfalleflickan** [fuhry/initramfs-scencrypt#26]
Hello! 

As far as I understand it, this does not support unlocking the root partition as it depends on /etc/crypttab - would it be possible (maybe with kernel parameters?) to allow unlocking in early userspace?

**Comment by fuhry** [comment]
The root filesystem is supported today - crypttab is copied to the initramfs and parsed there. If `/etc/crypttab.initramfs` exists, that is used, otherwise `/etc/crypttab` is used.
