### ISSUE TITLE
gpg in install hook returns two key ids

### ISSUE THREAD

**Issue by ascii78** [fuhry/initramfs-scencrypt#8]
This call in install hook returns both ID and keyid for me, so $keyid can not be used for $keyfile later

https://github.com/fuhry/initramfs-scencrypt/blob/d1b53ca254b576ae6f1cdc2d5a2da6863def069e/scencrypt-install#L45

I've removed "ID" locally which works, but maybe adding "uniq" is better.

Maybe the output has changed ? This is with 2.2.5...

```
gpg: encrypted with 4096-bit RSA key, ID 12345etc , created 2018-04-04
      "First Last <firs.last@example.com>"
# off=0 ctb=85 tag=1 hlen=3 plen=524
:pubkey enc packet: version 3, algo 1, keyid 1234etc
        data: [4095 bits]
# off=527 ctb=d2 tag=18 hlen=2 plen=126 new-ctb
:encrypted data packet:
        length: 126
        mdc_method: 2
```

Just noticed that manual also mentions that output may indeed change with version.

**Comment by fuhry** [comment]
Hey, for some reason GitHub isn't sending me email notifications and I never saw this.

This issue should be fixed in commit a01f9d5b20771a0aea8a6165bc0d1cac6b53f287. If not can you please reopen? Thanks!
